# NOTE: update this with your service name
service: agol-webhook

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  profile: ${self:custom.profiles.${self:provider.stage}}
  deploymentBucket:
    name: serverless-deployment-bucket-p389201dj
    serverSideEncryption: AES256

custom:
  deploymentBucket:
    blockPublicAccess: true
  profiles:
    dev: serverless-deploymentagent
    prod: prodProfile

functions:
  hello:
    handler: lib/handlers/handler.hello
    events:
      - http:
          path: hello
          method: post
