service: agol-webhook

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  profile: ${self:custom.profiles.${self:provider.stage}}
  deploymentBucket:
    name: serverless-deployment-bucket-p389201dj
    serverSideEncryption: AES256
    blockPublicAccess: true

custom:
  deploymentBucket:
    blockPublicAccess: true
  profiles:
    dev: serverless-deploymentagent
    prod: prodProfile
  bundle:
    linting: false

functions:
  webhook_api:
    description: "This receives a payload from an ArcGIS Online webhook and processes it."
    memorySize: 256 # memorySize for this specific function.
    handler: lib/handlers/handler.handleWebhook
    environment: ${file(./env.yml):${self:provider.stage}}      
    events:
      - http:
          path: webhook/{webhook_id}
          method: post
          cors:
            origin: https://*arcgis.com
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent

            allowCredentials: false

resources:
  #API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}